[build]
  functions = "netlify/functions"
  publish = "dist"
  command = "npx vite build"

[functions]
  node_bundler = "esbuild"

[functions."*"]
  timeout = 26

# ✅ スケジューラー設定
[[functions]]
  name = "scheduler"
  schedule = "*/1 * * * *"
