[build]
  functions = "netlify/functions"
  publish = "dist"
  command = "npx vite build"

[functions]
  node_bundler = "esbuild"
  timeout = 26

# ✅ スケジューラー設定（個別関数）
[[functions]]
  name = "scheduler"
  schedule = "*/1 * * * *"
